//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBookingTicket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusDetail
    {
        public BusDetail()
        {
            this.BusSeatTypeMaps = new HashSet<BusSeatTypeMap>();
            this.Reservations = new HashSet<Reservation>();
            this.RoutePrices = new HashSet<RoutePrice>();
        }
    
        public int BusId { get; set; }
        public Nullable<int> BusNumber { get; set; }
        public Nullable<int> NoOfSeats { get; set; }
        public string BusType { get; set; }
        public Nullable<System.TimeSpan> BusTime { get; set; }
        public Nullable<int> BusCompanyId { get; set; }
        public Nullable<int> routeId { get; set; }
    
        public virtual BusCompany BusCompany { get; set; }
        public virtual Route Route { get; set; }
        public virtual ICollection<BusSeatTypeMap> BusSeatTypeMaps { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<RoutePrice> RoutePrices { get; set; }
    }
}
