//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBookingTicket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusSeatTypeMap
    {
        public int id { get; set; }
        public int BusId { get; set; }
        public Nullable<int> SeatTypeId { get; set; }
        public Nullable<int> TotalSeatCount { get; set; }
    
        public virtual BusDetail BusDetail { get; set; }
        public virtual SeatType SeatType { get; set; }
    }
}
