//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBookingTicket.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusBookingTicketEntities : DbContext
    {
        public BusBookingTicketEntities()
            : base("name=BusBookingTicketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BoardingPoint> BoardingPoints { get; set; }
        public DbSet<BusCompany> BusCompanies { get; set; }
        public DbSet<BusDetail> BusDetails { get; set; }
        public DbSet<BusSeatTypeMap> BusSeatTypeMaps { get; set; }
        public DbSet<CityDetail> CityDetails { get; set; }
        public DbSet<PassangerDetail> PassangerDetails { get; set; }
        public DbSet<PayMentDetail> PayMentDetails { get; set; }
        public DbSet<Reservation> Reservations { get; set; }
        public DbSet<Route> Routes { get; set; }
        public DbSet<RoutePrice> RoutePrices { get; set; }
        public DbSet<SeatType> SeatTypes { get; set; }
        public DbSet<StateDetail> StateDetails { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
    }
}
