//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBookingTicket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassangerDetail
    {
        public PassangerDetail()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Passangerid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> TicketNumber { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
