//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBookingTicket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayMentDetail
    {
        public PayMentDetail()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> CVV { get; set; }
        public Nullable<byte> ExpiryMonth { get; set; }
        public string NameOfCardHolder { get; set; }
        public Nullable<int> ExpiryYear { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
