//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBookingTicket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int TicketId { get; set; }
        public Nullable<int> routeId { get; set; }
        public Nullable<int> passangerId { get; set; }
        public Nullable<int> BusId { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
        public Nullable<int> SeatNumber { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BoardingPointId { get; set; }
        public Nullable<int> PaymentDetailsId { get; set; }
    
        public virtual BoardingPoint BoardingPoint { get; set; }
        public virtual BusDetail BusDetail { get; set; }
        public virtual PassangerDetail PassangerDetail { get; set; }
        public virtual PayMentDetail PayMentDetail { get; set; }
        public virtual Route Route { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
