//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBookingTicket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.BusDetails = new HashSet<BusDetail>();
            this.Reservations = new HashSet<Reservation>();
            this.RoutePrices = new HashSet<RoutePrice>();
        }
    
        public int id { get; set; }
        public int FromCityId { get; set; }
        public int ToCityId { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<System.TimeSpan> DepartureTime { get; set; }
        public Nullable<System.TimeSpan> ArrivalTime { get; set; }
    
        public virtual ICollection<BusDetail> BusDetails { get; set; }
        public virtual CityDetail CityDetail { get; set; }
        public virtual CityDetail CityDetail1 { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<RoutePrice> RoutePrices { get; set; }
    }
}
