//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBookingTicket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatType
    {
        public SeatType()
        {
            this.BusSeatTypeMaps = new HashSet<BusSeatTypeMap>();
            this.RoutePrices = new HashSet<RoutePrice>();
        }
    
        public int id { get; set; }
        public string SeatType1 { get; set; }
    
        public virtual ICollection<BusSeatTypeMap> BusSeatTypeMaps { get; set; }
        public virtual ICollection<RoutePrice> RoutePrices { get; set; }
    }
}
