//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBookingTicket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateDetail
    {
        public StateDetail()
        {
            this.CityDetails = new HashSet<CityDetail>();
        }
    
        public string StateName { get; set; }
        public int StateId { get; set; }
    
        public virtual ICollection<CityDetail> CityDetails { get; set; }
    }
}
